### ISSUE TITLE
About closed explicity and EOF errors

### ISSUE THREAD

**Issue by inancgumus** [ti/mdb#1]
You can close this issue immediately. I'm just writing here for your suggestions.

I saw that you had (have been?) the same problem as I. I put an issue [here](https://github.com/go-mgo/mgo/issues/473), can you look at it and tell me your thoughts? Is `mgb` correct solution to this problem (_as I guess so_)?

**Comment by ti** [comment]
i am just change the mgo driver to "github.com/globalsign/mgo", globalsign is the best backend for mdb
